/*
Materi Looping Javascript
! PERULANGAN DI JAVASCIPT
? for, for of, for in, foreach
* While & Do While
**/

for(let Data = 1; Data <= 5; Data++) {     
    console.log('Urutan Data -', Data)                                    // Ini adalah cara looping sederhana
}

// Urutan data - 1   --------------- z  = 2
// Urutan data - 2   --------------- z  = 3
// Urutan data - 3   --------------- z  = 4
// Urutan data - 4   --------------- z  = 5
// Urutan data - 5   --------------- z  = 6

// z = 6 karena z sudah lebih dari sama dengan 5
// 👇👇👇
// end of loop tidak akan masuk 
